# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
<<<<<<< HEAD
=======
- dev
>>>>>>> 8aa3f426aed13664e662b940455bbaaadfaa0b18

pool:
  vmImage: 'ubuntu-latest'

steps:
<<<<<<< HEAD
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
=======
- script: python3 runTest.py
  timeoutInMinutes: 180
  displayName: 'Running test'
>>>>>>> 8aa3f426aed13664e662b940455bbaaadfaa0b18
